sitesite_homepage:
    path:       /
    defaults:   { _controller: sitesiteBundle:Default:index }

site_pageweb_categories:
    path:       /page/categories/{categorieSlug}/{params}
    defaults:   { _controller: sitesiteBundle:Default:pagewebCategorie, params: null }

site_pageweb:
    path:       /page/{pagewebSlug}/{params}
    defaults:   { _controller: sitesiteBundle:Default:pagewebPageweb, params: null }



site_pageweb_categorie:
    path:       /categorie/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:categorie, parentSlug: null }

site_pageweb_pageweb:
    path:       /pageweb/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:pageweb, parentSlug: null }

site_pageweb_article:
    path:       /article/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:article, parentSlug: null }

site_pageweb_articles:
    path:       /articles/{categorieSlug}
    defaults:   { _controller: sitesiteBundle:Default:articlesByCategorie }

site_pageweb_fiche:
    path:       /fiche/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:fiche, parentSlug: null }

site_pageweb_ficherecette:
    path:       /fiche-recette/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:fiche, parentSlug: null }

site_pageweb_ficheboisson:
    path:       /fiche-boisson/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:fiche, parentSlug: null }

site_pageweb_fiches:
    path:       /fiches/{categorieSlug}
    defaults:   { _controller: sitesiteBundle:Default:fichesByCategorie }

# AJAX LIVE
ajaxlive_global_serialized:
    path:       /global-serialized/{requirements}/{user}
    defaults:   { _controller: sitesiteBundle:ajaxlive:globalinfos, requirements: null, user: null }

entity_serialized:
    path:       /serialized/{requirements}/{user}/{shortname}
    defaults:   { _controller: sitesiteBundle:ajaxlive:entiteinfos, requirements: null, user: null, shortname: null }

# Gestion du panier
panier_action:
    path:       /panier/action/{getdata}
    defaults:   { _controller: sitesiteBundle:panier:panier, getdata: null }

panier_test_action:
    path:       /panier-test/action/{getdata}
    defaults:   { _controller: sitesiteBundle:panier:panierTest, getdata: null }

