sitesite_homepage:
    path:       /
    defaults:   { _controller: sitesiteBundle:Default:index }

site_pageweb_categories:
    path:       /page/categories/{categorieSlug}/{params}
    defaults:   { _controller: sitesiteBundle:Default:pagewebCategorie, params: null }

site_pageweb:
    path:       /page/{pagewebSlug}/{params}
    defaults:   { _controller: sitesiteBundle:Default:pagewebPageweb, params: null }



site_pageweb_categorie:
    path:       /categorie/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:categorie, parentSlug: null }

site_pageweb_pageweb:
    path:       /pageweb/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:pageweb, parentSlug: null }

site_pageweb_article:
    path:       /article/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:article, parentSlug: null }

site_pageweb_articles:
    path:       /articles/{categorieSlug}
    defaults:   { _controller: sitesiteBundle:Default:articlesByCategorie }

site_pageweb_fiche:
    path:       /fiche/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:fiche, parentSlug: null }

site_pageweb_ficherecette:
    path:       /fiche-recette/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:fiche, parentSlug: null }

site_pageweb_ficheboisson:
    path:       /fiche-boisson/{itemSlug}/{parentSlug}
    defaults:   { _controller: sitesiteBundle:Default:fiche, parentSlug: null }

site_pageweb_fiches:
    path:       /fiches/{categorieSlug}
    defaults:   { _controller: sitesiteBundle:Default:fichesByCategorie }


# Gestion du panier
panier_action:
    path:       /panier/action/{action}/{id}/{param}
    defaults:   { _controller: sitesiteBundle:panier:panier, action: 'add', id: null, param: null }

