# main_admin:
#     path: /{_locale}
#     defaults: { _controller: siteadminsiteBundle:Default:index, _locale: %locale% }
#     host: "admin.boucherie-du-veyron.fr"
#     requirements:
#         _locale: %default_locales%

# main_home:
#     path: /{_locale}
#     host: "www.boucherie-du-veyron.{ext}"
#     defaults: { _controller: sitesiteBundle:Default:index, _locale: %locale%, ext: 'fr' }
#     requirements:
#         _locale: %default_locales%
#         ext: fr|com





#############################
# boucherie-du-veyron
#############################

sitesiteBundle_bdv_path:
    path: /{_locale}
    defaults: { _controller: sitesiteBundle:Default:index, _locale: %locale% }
    host: "www.boucherie-du-veyron.{ext}"
    requirements:
        _locale: %default_locales%
        ext: fr|com

sitesiteBundle_www_bdv_fr:
    resource: "@sitesiteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults: { _locale: %locale%, ext: fr }
    host: "www.boucherie-du-veyron.{ext}"
    requirements:
        _locale: %default_locales%
        ext: fr|com

siteadminsiteBundle_bdv_path:
    path: /{_locale}
    defaults: { _controller: siteadminsiteBundle:Default:index, _locale: %locale% }
    host: "admin.boucherie-du-veyron.fr"
    requirements:
        _locale: %default_locales%
        ext: fr|com

siteadminsiteBundle_admin_bdv_fr:
    resource: "@siteadminsiteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults: { _locale: %locale% }
    host: "admin.boucherie-du-veyron.fr"
    requirements:
        _locale: %default_locales%


#############################
# localhost
#############################

sitesiteBundle_local_path:
    path: /{_locale}
    defaults: { _controller: sitesiteBundle:Default:index, _locale: %locale% }
    # host: "localhost"
    requirements:
        _locale: %default_locales%

sitesiteBundle_local:
    resource: "@sitesiteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults: { _locale: %locale% }
    # host: "localhost"
    requirements:
        _locale: %default_locales%

siteadminsiteBundle_local:
    resource: "@siteadminsiteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    defaults: { _locale: %locale% }
    # host: "localhost"
    requirements:
        _locale: %default_locales%




site_translate:
    resource: "@sitetranslateBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/translate
    requirements:
        _locale: %default_locales%

site_edition:
    resource: "@siteeditionBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/edition
    requirements:
        _locale: %default_locales%

site_user:
    resource: "@siteUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/user
    requirements:
        _locale: %default_locales%


# USER ROUTING
fos_user_admin:
    resource: "@FOSUserBundle/Resources/config/routing/admin.xml"
    prefix: /{_locale}
    requirements:
        _locale: %default_locales%

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
    requirements:
        _locale: %default_locales%

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: %default_locales%

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: %default_locales%

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: %default_locales%

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: %default_locales%
