# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    ae_services:           site\adminBundle\services\

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # fonctionnalités de réponse pour Ajax notamment
    aetools.aeReponse:
        class: %ae_services%aeReponse
        arguments: [@service_container]

    # fonctionnalités de base / boîte à outils
    aetools.aetools:
        class: %ae_services%aetools
        arguments: [@service_container]

    # fonctionnalités d'entités
    # aetools.aeEntities:
    #     class: %ae_services%aeEntities
    #     arguments: [@service_container]

    # fonctionnalités d'entités BIS
    aetools.aeEntity:
        class: %ae_services%aeEntity
        arguments: [@service_container]

    aetools.aeSubEntity:
        class: %ae_services%aeSubEntity
        arguments: [@service_container]

    # fonctionnalités de site
    aetools.aeSite:
        class: %ae_services%aeSite
        arguments: [@service_container]

    # fonctionnalités de categorie
    aetools.aeCategorie:
        class: %ae_services%aeCategorie
        arguments: [@service_container]

    # fonctionnalités de tag
    aetools.aeTag:
        class: %ae_services%aeTag
        arguments: [@service_container]

    # fonctionnalités de statut
    aetools.aeStatut:
        class: %ae_services%aeStatut
        arguments: [@service_container]

    # fonctionnalités de message
    aetools.aeMessage:
        class: %ae_services%aeMessage
        arguments: [@service_container]

    # fonctionnalités de panier
    aetools.aePanier:
        class: %ae_services%aePanier
        arguments: [@service_container]

    #######################
    ### ITEM            ###
    #######################

    # fonctionnalités de item
    aetools.aeItem:
        class: %ae_services%aeItem
        arguments: [@service_container]

    # fonctionnalités de article
    aetools.aeArticle:
        class: %ae_services%aeArticle
        arguments: [@service_container]

    # fonctionnalités de pageweb
    aetools.aePageweb:
        class: %ae_services%aePageweb
        arguments: [@service_container]

    # fonctionnalités de fiche
    aetools.aeFiche:
        class: %ae_services%aeFiche
        arguments: [@service_container]

    #######################
    ### TIER            ###
    #######################

    # fonctionnalités de tier
    aetools.aeTier:
        class: %ae_services%aeTier
        arguments: [@service_container]

    #######################
    ### MEDIA           ###
    #######################

    # fonctionnalités de media
    aetools.aeMedia:
        class: %ae_services%aeMedia
        arguments: [@service_container]

    # fonctionnalités de image
    aetools.aeImage:
        class: %ae_services%aeImage
        arguments: [@service_container]

    # fonctionnalités de pdf
    aetools.aePdf:
        class: %ae_services%aePdf
        arguments: [@service_container]

    # fonctionnalités de rawfile
    aetools.aeRawfile:
        class: %ae_services%aeRawfile
        arguments: [@service_container]



    #######################
    ### DEBUG           ###
    #######################

    # fonctionnalités de fixtures
    aetools.debug:
        class: %ae_services%aeDebug
        arguments: [@service_container]


    #######################
    ### FIXTURES        ###
    #######################

    # fonctionnalités de fixtures
    aetools.aefixtures:
        class: %ae_services%aeFixtures
        arguments: [@service_container]


    #######################
    ### TWIG EXTENSIONS ###
    #######################

    # Fonctions textes utiles et pratiques pour utilisation dans TWIG
    aetools.textutilities:
        class: %ae_services%twigTools
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    # Twig extension for dates
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }


    #######################
    ### SUCCESS HANDLER ###
    #######################

    # aetools.success_handler:
    #     class: %ae_services%SuccessHandler
    #     arguments: [@router, @service_container]
    #     public: false

    ###################################
    ### EVENT LISTENER SUR DOCTRINE ENTITIES
    ###################################

    # Utilitaire de gestion sur les entités
    # acmeGroup.entityUtils:
    #     class: %ae_services%entityListener
    #     arguments: [@service_container]
    #     tags:
    #         - { name: doctrine.event_listener, event: postLoad }
    #         - { name: doctrine.event_listener, event: prePersist }
    #         - { name: doctrine.event_listener, event: postPersist }
    #         - { name: doctrine.event_listener, event: preUpdate }
    #         - { name: doctrine.event_listener, event: postUpdate }
    #         - { name: doctrine.event_listener, event: preRemove }
    #         - { name: doctrine.event_listener, event: postRemove }

    ######################
    ### EVENT LISTENER ###
    ######################

    # EventListerner sur paramètres généraux du site
    # aetools.site_listener:
    #     class: %ae_services%siteListener
    #     # arguments: [@service_container]
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.controller, method: load }
