twig:
    globals:
        keywords:
            title: site.title
            description: site.description
            keywords: site.keywords
        formatDate:      "dd-MM-yyyy"
        formatDateHeure: "d-m-Y H:i:s"
        # fileFormats:
        #     pdf:        pdf
        #     jpg:        image
        #     jpeg:       image
        #     gif:        image
        #     png:        image
        #     default:    text
        default_icon: 'fa-caret-right'
        menu_Admin_default_role: %restrict_admin%
        menu_Admin:
            accueil:
                nom: 'accueil'
                path: siteadmin_homepage
                icon: 'fa-home'
            traduction:
                role: 'ROLE_TRANSLATOR'
                nom: 'traduction.name'
                path: 'sitetranslate_homepage'
                icon: 'fa-flag'
            marketplace:
                role: 'ROLE_ADMIN'
                nom: 'marketplace.name'
                path: 'siteadmin_homepage'
                icon: 'fa-shopping-cart'
                level2: 
                    article:
                        role: 'ROLE_ADMIN'
                        nom: 'article.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: article
                    marques:
                        role: 'ROLE_ADMIN'
                        nom: 'marque.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: marque
                    boutiques:
                        role: 'ROLE_ADMIN'
                        nom: 'boutique.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: boutique
                    reseaux:
                        role: 'ROLE_ADMIN'
                        nom: 'reseau.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: reseau
                    tauxTva:
                        role: 'ROLE_ADMIN'
                        nom: 'tauxTva.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: tauxTva
            pageweb:
                role: 'ROLE_EDITOR'
                nom: 'pageweb.name_s'
                path: 'siteadmin_homepage'
                icon: 'fa-desktop'
                level2: 
                    item0:
                        role: 'ROLE_EDITOR'
                        nom: 'pageweb.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: pageweb
                    item1:
                        role: %restrict_admin%
                        nom: 'menu.name_s'
                        trans_domain: menus
                        path: 
                            path: 'siteadmin_menus'
                            params:
                                name: all
            media:
                role: 'ROLE_EDITOR'
                nom: 'media.name_s'
                path: 'siteadmin_homepage'
                icon: 'fa-film'
                level2: 
                    images:
                        nom: 'image.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: image
                                # type_related: _self
                                # type_field: mediaType
                                # type_values: image
                    pdf:
                        nom: 'pdf.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: pdf
                                # type_related: _self
                                # type_field: mediaType
                                # type_values: pdf
                    fiches:
                        nom: 'fiche.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: fiche
                    tags:
                        nom: 'tag.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: tag
            utilisateurs:
                role: %restrict_admin%
                nom: 'User.name_s'
                path: 'site_user_homepage'
                icon: 'fa-users'
                level2: 
                    Tous:
                        nom: 'Tous'
                        path: 
                            path: 'siteUser_users'
                    Public:
                        nom: 'Public'
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_USER
                    Traducteur:
                        nom: 'Traducteur'
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_TRANSLATOR
                    Editeur:
                        nom: 'Editeur'
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_EDITOR
                    Administrateur:
                        nom: 'Administrateur'
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_ADMIN
                    SuperAdmin:
                        nom: 'Super admin'
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_SUPER_ADMIN
            messages:
                role: ROLE_EDITOR
                nom: message.name_s
                icon: fa-paper-plane
                path:
                    path: siteadmin_entite
                    params:
                        entite: message
            parametres:
                role: %restrict_admin%
                nom: 'parametres'
                path: 'siteadmin_homepage'
                icon: 'fa-gear'
                level2: 
                    fileFormat:
                        nom: 'fileFormat.name_s'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: fileFormat
            help:
                nom: 'help'
                path: siteadmin_support
                icon: 'fa-support'
            ROLE_SUPER_ADMIN:
                role: 'ROLE_SUPER_ADMIN'
                nom: 'superadmin.name'
                path: 'siteadmin_sadmin_index'
                icon: 'fa-cogs'
                level2: 
                    sadminHome:
                        nom: 'superadmin.name'
                        path: 'siteadmin_sadmin_index'
                    generate:
                        nom: 'install.name'
                        path: 'generate'
                    entities:
                        nom: 'superadmin.entites'
                        path: 'siteadmin_sadmin_entities'
