twig:
    globals:
        keywords:
            title: site.title
            description: site.description
            keywords: site.keywords
        formatDate:      "dd-MM-yyyy"
        formatDateHeure: "d-m-Y H:i:s"
        # fileFormats:
        #     pdf:        pdf
        #     jpg:        image
        #     jpeg:       image
        #     gif:        image
        #     png:        image
        #     default:    text
        default_icon: 'fa-caret-right'
        menu_Admin_default_role: %restrict_admin%
        menu_Admin:
            accueil:
                nom: 'accueil'
                path: siteadmin_homepage
                icon: 'fa-home'
            traduction:
                role: 'ROLE_TRANSLATOR'
                nom: 'traduction.name'
                path: 'sitetranslate_homepage'
                icon: 'fa-flag'
            marketplace:
                role: 'ROLE_ADMIN'
                nom: 'marketplace.name'
                path: 'siteadmin_homepage'
                icon: 'fa-shopping-cart'
                level2: 
                    article:
                        role: 'ROLE_ADMIN'
                        nom: 'name_s'
                        trans_domain: article
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: article
                    marques:
                        role: 'ROLE_ADMIN'
                        nom: 'name_s'
                        trans_domain: marque
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: marque
                    boutiques:
                        role: 'ROLE_ADMIN'
                        nom: 'name_s'
                        trans_domain: boutique
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: boutique
                    reseaux:
                        role: 'ROLE_ADMIN'
                        nom: 'name_s'
                        trans_domain: reseau
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: reseau
                    tauxTva:
                        role: 'ROLE_ADMIN'
                        nom: 'name_s'
                        trans_domain: tauxTva
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: tauxTva
            pageweb:
                role: 'ROLE_EDITOR'
                nom: 'name_s'
                trans_domain: pageweb
                path: 'siteadmin_homepage'
                icon: 'fa-desktop'
                level2: 
                    item0:
                        role: 'ROLE_EDITOR'
                        nom: 'name_s'
                        trans_domain: pageweb
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: pageweb
                    item1:
                        role: %restrict_admin%
                        nom: 'menu.name_s'
                        trans_domain: menus
                        path: 
                            path: 'siteadmin_menus'
                            params:
                                name: all
            media:
                role: 'ROLE_EDITOR'
                nom: 'name_s'
                trans_domain: media
                path: 'siteadmin_homepage'
                icon: 'fa-film'
                level2: 
                    images:
                        nom: 'name_s'
                        trans_domain: image
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: image
                                # type_related: _self
                                # type_field: mediaType
                                # type_values: image
                    pdf:
                        nom: 'name_s'
                        trans_domain: pdf
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: pdf
                                # type_related: _self
                                # type_field: mediaType
                                # type_values: pdf
                    fiches:
                        nom: 'name_s'
                        trans_domain: fiche
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: fiche
                    tags:
                        nom: 'name_s'
                        trans_domain: tag
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: tag
                    raws:
                        nom: 'raw files'
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: rawfile
            utilisateurs:
                role: %restrict_admin%
                nom: 'name_s'
                trans_domain: User
                path: 'site_user_homepage'
                icon: 'fa-users'
                level2: 
                    Tous:
                        nom: 'roles.ALL'
                        trans_domain: User
                        path: 
                            path: 'siteUser_users'
                    Public:
                        nom: 'roles.ROLE_USER'
                        trans_domain: User
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_USER
                    Traducteur:
                        nom: 'roles.ROLE_TRANSLATOR'
                        trans_domain: User
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_TRANSLATOR
                    Editeur:
                        nom: 'roles.ROLE_EDITOR'
                        trans_domain: User
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_EDITOR
                    Administrateur:
                        nom: 'roles.ROLE_ADMIN'
                        trans_domain: User
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_ADMIN
                    SuperAdmin:
                        nom: 'roles.ROLE_SUPER_ADMIN'
                        trans_domain: User
                        path: 
                            path: 'siteUser_users'
                            params:
                                type: ROLE_SUPER_ADMIN
                    Adresses:
                        nom: 'name_s'
                        trans_domain: adresse
                        path: 
                            path: siteadmin_entite
                            params:
                                entite: adresse
            messages:
                role: %restrict_admin%
                nom: name_s
                trans_domain: message
                icon: fa-paper-plane
                path:
                    path: siteadmin_entite
                    params:
                        entite: message
            parametres:
                role: %restrict_admin%
                nom: 'parametres'
                path: 'siteadmin_homepage'
                icon: 'fa-gear'
                level2: 
                    fileFormat:
                        nom: 'name_s'
                        trans_domain: fileFormat
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: fileFormat
                    statut:
                        role: 'ROLE_SUPER_ADMIN'
                        nom: 'name_s'
                        trans_domain: statut
                        path: 
                            path: 'siteadmin_entite'
                            params:
                                entite: statut
            help:
                nom: 'help'
                path: siteadmin_support
                icon: 'fa-support'
            webmaster:
                role: 'ROLE_SUPER_ADMIN'
                nom: 'roles.ROLE_SUPER_ADMIN'
                trans_domain: User
                path: 'siteadmin_sadmin_index'
                icon: 'fa-cogs'
                level2: 
                    sadminHome:
                        nom: 'roles.ROLE_SUPER_ADMIN'
                        trans_domain: User
                        path: 'siteadmin_sadmin_index'
                    generate:
                        nom: 'install.name'
                        path: 'generate'
                    routes:
                        nom: 'Routes'
                        path: 'siteadmin_sadmin_routes'
                    bundles:
                        nom: 'Bundles'
                        path: 'siteadmin_sadmin_bundles'
                    entities:
                        nom: 'superadmin.entites'
                        path: 'siteadmin_sadmin_entities'
