parameters:
#    siteadminsite.example.class: site\adminsiteBundle\Example

services:
#    siteadminsite.example:
#        class: %siteadminsite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
