<?php

namespace site\adminsiteBundle\Entity;

use Labo\Bundle\AdminBundle\Entity\itemRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Labo\Bundle\AdminBundle\services\aetools;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends itemRepository {

	public function defaultValsListClosure(aetools $aeEntities = null, $data = null, $entity = NULL) {
		$qb = parent::defaultValsListClosure($aeEntities, $data, $entity);
		if(is_object($data)) {
			$id = $data->getId();
			if($id != null) {
				// exclut lui-même
				$qb->andWhere(self::ELEMENT.'.id != :id')
					->setParameter('id', $id)
					;
			}
		}
		// resultat
		return $qb;
	}

}
