<?php

namespace site\adminBundle\Entity;

use site\adminBundle\Entity\itemRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

use site\adminBundle\services\aetools;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends itemRepository {

	public function defaultValsListClosure(aetools $aeEntities = null, $data = null) {
		$qb = parent::defaultValsListClosure($aeEntities, $data);
		if(is_object($data)) {
			$id = $data->getId();
			if($id != null) {
				// exclut lui-même
				$qb->andWhere(self::ELEMENT.'.id != :id')
					->setParameter('id', $id)
					;
			}
		}
		// $this->sortByPosition($qb);
		// resultat
		return $qb;
	}

	public function sortByPosition(&$qb) {
		$qb->join(self::ELEMENT.'.articlepositionParents', 'ap')
			->orderBy('ap.position', 'ASC')
		;
	}

}
