<?php

namespace site\adminBundle\Entity;

// use site\adminBundle\Entity\baseSubEntityRepository;
use Gedmo\Sortable\Entity\Repository\SortableRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * articlepositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articlepositionRepository extends SortableRepository {

	const ELEMENT = 'element';

	public function existsJointure($parent, $child) {
		if(is_object($parent)) $parent = $parent->getId();
		if(is_object($child)) $child = $child->getId();
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb->join(self::ELEMENT.'.parent', 'parent')
			->where('parent.id = :parentid')
			->setParameter('parentid', $parent)
			->join(self::ELEMENT.'.child', 'child')
			->andWhere('child.id = :childid')
			->setParameter('childid', $child)
			// ->select(self::ELEMENT.'.position')
			;
		$result = $qb->getQuery()->getScalarResult();
		return count($result) > 0;
	}

}
