<?php

namespace site\adminBundle\Entity;

use site\adminBundle\Entity\EntityBaseRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

// use site\adminBundle\Entity\article;
// use site\adminBundle\Entity\image;
// use site\adminBundle\Entity\pdf;
// use site\adminBundle\Entity\marque;
// use site\adminBundle\Entity\reseau;
// use site\adminBundle\Entity\boutique;
// use site\adminBundle\Entity\pageweb;

/**
 * baseSubEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class baseSubEntityRepository extends EntityBaseRepository {


	/********************************/
	/*** CLOSURES                 ***/
	/********************************/

	public function getElementsBySubTypes($categories) {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$types = array();
		if(is_object($categories)) $categories = array($categories);
		foreach ($categories as $categorie) {
			$types = array_merge($types, $categorie->getAccepts());
		}
		foreach (array_unique($types) as $type) {
			if(is_string($type)) $qb->orWhere($qb->expr()->isInstanceOf(self::ELEMENT, 'site\\adminBundle\\Entity\\'.$type));
		}
		// resultat
		return $qb;
	}




}
