<?php

namespace site\adminBundle\Entity;

use site\adminBundle\Entity\EntityBaseRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messageRepository extends EntityBaseRepository {

	public function findAll() {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb->orderBy(self::ELEMENT.'.creation', 'DESC');
		return $qb->getQuery()->getResult();
	}

	public function findNotRead() {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb
			->where($qb->expr()->isNull('element.read'))
			->orderBy(self::ELEMENT.'.creation', 'DESC')
			;
		return $qb->getQuery()->getResult();
	}

}
