<?php

namespace site\adminBundle\Entity;

use site\adminBundle\Entity\EntityBaseRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierRepository extends EntityBaseRepository {

	private $userId;

	public function setUser($user) {
		$this->userId = $user;
	}

	public function getUserArticles($userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->leftJoin('element.user', 'user')
			->where('user.id = :u')
			->setParameter('u', $userId)
			// ->addSelect('user')
			->leftJoin('element.article', 'art')
			->addSelect('art');
		return $qb->getQuery()->getResult();
	}

	public function getUserPanier($userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->leftJoin('element.user', 'user')
			->where('user.id = :u')
			->setParameter('u', $userId);
		return $qb->getQuery()->getResult();
	}

	public function getOneArticleOfUser($articleId, $userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.user = :u')
			->setParameter('u', $userId)
			->andWhere('element.article = :art')
			->setParameter('art', $articleId);
		return $qb->getQuery()->getOneOrNullResult();
	}

}
