<?php

namespace site\adminBundle\Entity;

use site\adminBundle\Entity\baseSubEntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * rawfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rawfileRepository extends baseSubEntityRepository {

	/**
	 * Renvoie tous les rawfile qui ont un statut temporaire
	 * @param array $listOfId = null
	 * @return array
	 */
	public function findTempStatut($listOfId = null) {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb->join(self::ELEMENT.'.statut', 'stat')
			->where($qb->expr()->in('stat.nom', array('Temp')));
		if(is_array($listOfId))
			if(count($listOfId) < 1) return array();
			if(count($listOfId) > 0) $qb->andWhere($qb->expr()->in(self::ELEMENT.'.id', $listOfId));
		return $qb->getQuery()->getResult();
	}

}
