<?php

namespace site\adminBundle\Entity;

use Doctrine\ORM\QueryBuilder;
// use Doctrine\ORM\EntityRepository;
use site\adminBundle\Entity\EntityBaseRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Symfony\Component\DependencyInjection\ContainerInterface;

// use site\adminBundle\services\aetools;
// use site\adminBundle\services\aeEntity;
// use site\UserBundle\Entity\User;

use \DateTime;

/**
 * siteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class siteRepository extends EntityBaseRepository {

}
