<?php

namespace site\adminBundle\Entity;

use site\adminBundle\Entity\EntityBaseRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * statutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statutRepository extends EntityBaseRepository {

	/** Renvoie la(les) valeur(s) par défaut --> ATTENTION : dans un array()
	* @param $defaults = liste des éléments par défaut
	*/
	// public function defaultVal($defaults = null) {
	// 	if($defaults === null) $defaults = array("actif");
	// 	$qb = $this->createQueryBuilder(self::ELEMENT);
	// 	$qb->where($qb->expr()->in(self::ELEMENT.'.slug', $defaults));
	// 	return $qb->getQuery()->getOneOrNullResult();
	// }

	public function findActif() {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb->where(self::ELEMENT.'.slug = :slug')
			->setParameter('slug', 'actif');
		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findInactif() {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb->where(self::ELEMENT.'.slug = :slug')
			->setParameter('slug', 'inactif');
		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findExpired() {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb->where(self::ELEMENT.'.slug = :slug')
			->setParameter('slug', 'expired');
		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findDeleted() {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb->where(self::ELEMENT.'.slug = :slug')
			->setParameter('slug', 'deleted');
		return $qb->getQuery()->getOneOrNullResult();
	}

	public function defaultValClosure($role = "ROLE_USER") {
		$list = null;
		switch($role) {
			case "ROLE_EDITOR":
				$list = array("actif", "inactif", "expired");
				break;
			case "ROLE_USER":
				$list = array("actif", "inactif", "expired");
				break;
			case "ROLE_ADMIN":
				$list = array("actif", "inactif", "expired");
				break;
			case "ROLE_SUPER_ADMIN":
				// all
				break;
			default:
				$list = array("actif", "inactif", "expired");
				break;
		}
		$qb = $this->createQueryBuilder(self::ELEMENT);
		if(is_array($list)) $qb->where($qb->expr()->in(self::ELEMENT.'.slug', $list));
		return $qb;
	}

}
