<?php

namespace site\adminBundle\Entity;

use site\adminBundle\Entity\EntityBaseRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * tauxTvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tauxTvaRepository extends EntityBaseRepository {

	/**
	* defaultVal
	* Renvoie le taux de TVA par défaut (ou null)
	*/
	public function defaultVal() {
		$qb = $this->createQueryBuilder(self::ELEMENT)
			->where(self::ELEMENT.'.nom = :n')
			->setParameter('n', "normal");
		return $qb->getQuery()->getOneOrNullResult();
	}

}
