<?php

namespace site\adminBundle\Entity;

use site\adminBundle\Entity\EntityBaseRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * tauxTvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tauxTvaRepository extends EntityBaseRepository {

	/**
	 * defaultValAsClosure
	 * Renvoie le taux de TVA par défaut (ou null)
	 * @return QueryBuilder
	 */
	// public function defaultValAsClosure() {
	// 	$qb = $this->createQueryBuilder(self::ELEMENT)
	// 		->where(self::ELEMENT.'.nom = :n')
	// 		->setParameter('n', "normal");
	// 	return $qb;
	// }

}
